# Laboratorio 7

integrantes: 

- Francis Aguilar #22243

- Gerardo Pineda #22808

- Angela Garcia #22869

enlace al repositorio: https://github.com/angelargd8/LAB7-IA


# Task 1 - Teoría

1. ¿Qué es el temporal difference learning y en qué se diferencia de los métodos tradicionales de aprendizaje 
supervisado? Explique el concepto de "error de diferencia temporal" y su papel en los algoritmos de 
aprendizaje por refuerzo 

    El temporal difference learning es un método que combina las ideas del aprendizaje dinámico y del aprendizaje supervisado.
    Este tipo de aprendizaje esta basado en aprender a estimar valores futuros miestras va interactuando con un entorno, en vez de
    esperar hasta el final de una secuencia para ajustar las predicciones. Lo que hace es actualizar gradualmente las estimaciones en 
    función de las diferencias entre predicciones consecutivas. Entonces, las diferencias se usan para ajustar el modelo en tiempo real.
    Acerca del concepto de error de diferencia temporal, esta en los algoritmos de aprendizaje por refuerzo, porque lo que mide es la discrepancia entre la recompensa esperada y la obtenida. 


2. En el contexto de los juegos simultáneos, ¿cómo toman decisiones los jugadores sin conocer las acciones 
de sus oponentes? De un ejemplo de un escenario del mundo real que pueda modelarse como un juego 
simultáneo y discuta las estrategias que los jugadores podrían emplear en tal situación 

    En los juegos simultáneos un jugador al no conocer las acciones del oponente, busca estrategias considerando las posibles acciones del oponente, 
    pensando en obtener la mejor recompensa posible y muchas veces se toma en cuenta que al realizar una accion no dar pistas al oponente.
    Los jugadores también pueden tomar decisiones en función de la información disponible, como por ejemplo, el estado del juego, 
    pero también pueden tomar decisiones basadas en su conocimiento del entorno y de la estrategia de sus oponentes.
    Un ejemplo del mundo real es el juego de werewolf en el que los jugadores no saben el rol de los demás jugadores, y deben tomar decisiones
    a base sin saber si son humanos o lobos, entonces tratan de tomar acciones que no demuestren que rol tienen y simular que todos son humanos, 
    las acciones en este caso son en las votaciones, porque al decir que alguien es el lobo tiene que tener sentido, ya que al no tenerlo lo pueden 
    juzgar que es el lobo y terminar muerto dentro del juego. Mientras que los lobos, deben de ser cautelosos al matar a alguien, ya que si se descubren los acusaran de ser el lobo y terminarán muertos.


3. ¿Qué distingue los juegos de suma cero de los juegos de suma no cero y cómo afecta esta diferencia al 
proceso de toma de decisiones de los jugadores? Proporcione al menos un ejemplo de juegos que entren 
en la categoría de juegos de no suma cero y discuta las consideraciones estratégicas únicas involucradas 

    Lo que distingue a los juegos de suma cero de los juegos de suma de cero son en que los juegos de suma cero los 
    jugadores suelen actuar de una manera más competitiva porque no hay beneficios que se puedan compartir.
    Mientras, en los juegos de suma no cero los jugadores pueden buscar estrategias colaborativas porque hay beneficios que se pueden compartir.

    Un ejemplo de los juegos de suma no cero es Genshin impact, porque en este se pueden hacer partidas colaborativas en donde 
    ambos jugadores obtengan beneficios, como por ejemplo, obtener recompensas, subir de nivel y objeto. Entonces, al entrar a alguna
    mundo de otro jugador o cuando entran al mundo de uno, los jugadores pueden buscar una estrategia que maximice sus beneficios y minimice los beneficios de los demás. Incluso otro ejemplo es minecraft en donde muchas veces se juega multijugador mientras uno cumple el rol de construir la casa, otro exploración y otro minar, para obtener mayores recursos y compartirlos.



4. ¿Cómo se aplica el concepto de equilibrio de Nash a los juegos simultáneos? Explicar cómo el equilibrio de 
Nash representa una solución estable en la que ningún jugador tiene un incentivo para desviarse 
unilateralmente de la estrategia elegida 

    El concepto de equilibrio de Nash se aplica en los juegos simultáneos porque los jugadores toman decisiones al mismo tiempo sin conocer las elecciones de los demás. Las aplicaciones están en la elección de estrategias ótimas cuando el jugador escoge su mejor respuesta para maximizar su utilidad a base de lo que los demás están haciendo. También, se aplica en la evaluación de posibles combinaciones para encontrar el equilibrio, evaluando las posibles combinaciones de estrategias, identificando las que en donde ninguna de las partes pueda mejorar su resultado cambiando su estrategia.



5. Discuta la aplicación del temporal difference learning en el modelado y optimización de procesos de toma 
de decisiones en entornos dinámicos. ¿Cómo maneja el temporal difference learning el equilibrio entre 
exploración y explotación y cuáles son algunos de los desafíos asociados con su implementación en la 
práctica? 

    El temporal difference learning se usa en varios campos, como en la robótica, gestión de recursos y optimización de procesos industriales. Los agentes usan el temporal difference learning para ajustar sus politicas de acción basándose en las recompensas recibidas. Entonces, esto permite una adaptación continua y mejora en la toma de desiciones, esto ayuda al entorno ya que son dinámicos. 

    Acerca de como maneja el temporal difference learning el equilibrio y explotación, es que este maneja el equilibrio por varias estrategias que permiten al agente aprender de manera efectiva en entornos dinámicos, como la estrategia de Epsilon-Greedy y Softmax.
    Los desafíos que puede tener este es en el ajuste de parámetros, ya que determinar el valor óptimo de ε o los parámetros de la función softmax puede ser muy complicado y depende del entorno específico. También en el balance dinámico porque los entornos que cambian muy rápidamente, el equilibrio entre exploración y explotación puede necesitar ajustes contunios para irse adaptando a las nuevas condiciones. Por último, es importante asegurar que el agente explore lo suficiente para descubrir todas las posibles acciones y las consecuencias que tiene.





## Imports

In [1]:
import numpy as np
import random
import math
from IPython.display import clear_output
import numpy as np
import random
import pickle
import matplotlib.pyplot as plt


In [3]:
class Conecta4:
    FILAS = 6
    COLUMNAS = 7
    JUGADOR = 1
    IA = 2

    def __init__(self):
        self.tablero = np.zeros((self.FILAS, self.COLUMNAS), dtype=int)  

    def imprimir_tablero(self):
        print(np.flip(self.tablero, 0)) 

    def es_movimiento_valido(self, columna):
        return self.tablero[self.FILAS - 1, columna] == 0  

    def obtener_fila_disponible(self, columna):
        for fila in range(self.FILAS):
            if self.tablero[fila, columna] == 0:
                return fila
        return None  

    def realizar_movimiento(self, columna, jugador):
        if not self.es_movimiento_valido(columna):
            return False  
        fila = self.obtener_fila_disponible(columna)
        self.tablero[fila, columna] = jugador
        return True

    def verificar_victoria(self, jugador):
        for fila in range(self.FILAS):
            for col in range(self.COLUMNAS - 3):
                if all(self.tablero[fila, col + i] == jugador for i in range(4)):
                    return True

        for col in range(self.COLUMNAS):
            for fila in range(self.FILAS - 3):
                if all(self.tablero[fila + i, col] == jugador for i in range(4)):
                    return True

        for fila in range(self.FILAS - 3):
            for col in range(self.COLUMNAS - 3):
                if all(self.tablero[fila + i, col + i] == jugador for i in range(4)):
                    return True

        for fila in range(3, self.FILAS):
            for col in range(self.COLUMNAS - 3):
                if all(self.tablero[fila - i, col + i] == jugador for i in range(4)):
                    return True

        return False  

    def tablero_lleno(self):
        return np.all(self.tablero != 0)

    def obtener_movimientos_validos(self):
        return [c for c in range(self.COLUMNAS) if self.es_movimiento_valido(c)]

    def clonar_tablero(self):
        nuevo = Conecta4()
        nuevo.tablero = np.copy(self.tablero)
        return nuevo

# ====================== PRUEBA ======================
if __name__ == "__main__":
    tablero = Conecta4()
    tablero.imprimir_tablero()

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [4]:
import numpy as np
import random
import pickle  # para guardar la Q-table

class AgenteTD:
    def __init__(self, jugador=2, alpha=0.1, gamma=0.9, epsilon=0.1):
        self.jugador = jugador  # 1 o 2
        self.Q = {}  # Q[(estado, acción)] = valor
        self.alpha = alpha
        self.gamma = gamma
        self.epsilon = epsilon

    def obtener_estado(self, tablero):
        """Convierte el tablero a una tupla hashable"""
        return tuple(tablero.flatten())

    def elegir_accion(self, juego):
        """Estrategia ε-greedy"""
        estado = self.obtener_estado(juego.tablero)
        acciones = juego.obtener_movimientos_validos()

        if random.random() < self.epsilon:
            return random.choice(acciones)
        
        # Seleccionar acción con mayor Q
        valores = [self.Q.get((estado, a), 0) for a in acciones]
        max_q = max(valores)
        mejores = [a for a, q in zip(acciones, valores) if q == max_q]
        return random.choice(mejores)

    def actualizar(self, estado, accion, recompensa, nuevo_estado, acciones_siguientes):
        max_q_nuevo = max([self.Q.get((nuevo_estado, a), 0) for a in acciones_siguientes], default=0)
        valor_actual = self.Q.get((estado, accion), 0)
        self.Q[(estado, accion)] = valor_actual + self.alpha * (recompensa + self.gamma * max_q_nuevo - valor_actual)

    def guardar(self, archivo='qtable.pkl'):
        with open(archivo, 'wb') as f:
            pickle.dump(self.Q, f)

    def cargar(self, archivo='qtable.pkl'):
        try:
            with open(archivo, 'rb') as f:
                self.Q = pickle.load(f)
        except FileNotFoundError:
            print("Q-table no encontrada. Se iniciará una vacía.")


In [5]:
def tres_en_linea(tablero, jugador):
    conteo = 0

    # Horizontal
    for fila in range(tablero.FILAS):
        for col in range(tablero.COLUMNAS - 3):
            ventana = tablero.tablero[fila, col:col+4]
            if np.count_nonzero(ventana == jugador) == 3 and np.count_nonzero(ventana == 0) == 1:
                conteo += 1

    # Vertical
    for col in range(tablero.COLUMNAS):
        for fila in range(tablero.FILAS - 3):
            ventana = tablero.tablero[fila:fila+4, col]
            if np.count_nonzero(ventana == jugador) == 3 and np.count_nonzero(ventana == 0) == 1:
                conteo += 1

    # Diagonal positiva
    for fila in range(tablero.FILAS - 3):
        for col in range(tablero.COLUMNAS - 3):
            ventana = [tablero.tablero[fila + i, col + i] for i in range(4)]
            if ventana.count(jugador) == 3 and ventana.count(0) == 1:
                conteo += 1

    # Diagonal negativa
    for fila in range(3, tablero.FILAS):
        for col in range(tablero.COLUMNAS - 3):
            ventana = [tablero.tablero[fila - i, col + i] for i in range(4)]
            if ventana.count(jugador) == 3 and ventana.count(0) == 1:
                conteo += 1

    return conteo


In [5]:
# Entrenamiento del agente TD jugando contra un oponente aleatorio

#
agente_td = AgenteTD(jugador=Conecta4.IA)
oponente = Conecta4.JUGADOR

episodios = 50000 

for episodio in range(episodios):
    juego = Conecta4()
    estado = agente_td.obtener_estado(juego.tablero)
    turno = agente_td.jugador

    while not juego.tablero_lleno():
        if turno == agente_td.jugador:
            accion = agente_td.elegir_accion(juego)
            juego.realizar_movimiento(accion, agente_td.jugador)

            if juego.verificar_victoria(agente_td.jugador):
                recompensa = 1
                nuevo_estado = agente_td.obtener_estado(juego.tablero)
                agente_td.actualizar(estado, accion, recompensa, nuevo_estado, [])
                break

            nuevo_estado = agente_td.obtener_estado(juego.tablero)
            acciones_siguientes = juego.obtener_movimientos_validos()
            agente_td.actualizar(estado, accion, 0, nuevo_estado, acciones_siguientes)
            estado = nuevo_estado
            turno = oponente

        else:
            accion_oponente = random.choice(juego.obtener_movimientos_validos())
            juego.realizar_movimiento(accion_oponente, oponente)
            if juego.verificar_victoria(oponente):
                recompensa = -1
                nuevo_estado = agente_td.obtener_estado(juego.tablero)
                agente_td.actualizar(estado, accion, recompensa, nuevo_estado, [])
                break
            turno = agente_td.jugador

    # Recompensa por empate si el tablero se llena y no hubo victoria
    if juego.tablero_lleno() and not juego.verificar_victoria(agente_td.jugador) and not juego.verificar_victoria(oponente):
        agente_td.actualizar(estado, accion, 0.5, agente_td.obtener_estado(juego.tablero), [])

    if (episodio + 1) % 1000 == 0:
        print(f"Episodio {episodio + 1} completado.")


Episodio 1000 completado.
Episodio 2000 completado.
Episodio 3000 completado.
Episodio 4000 completado.
Episodio 5000 completado.
Episodio 6000 completado.
Episodio 7000 completado.
Episodio 8000 completado.
Episodio 9000 completado.
Episodio 10000 completado.
Episodio 11000 completado.
Episodio 12000 completado.
Episodio 13000 completado.
Episodio 14000 completado.
Episodio 15000 completado.
Episodio 16000 completado.
Episodio 17000 completado.
Episodio 18000 completado.
Episodio 19000 completado.
Episodio 20000 completado.
Episodio 21000 completado.
Episodio 22000 completado.
Episodio 23000 completado.
Episodio 24000 completado.
Episodio 25000 completado.
Episodio 26000 completado.
Episodio 27000 completado.
Episodio 28000 completado.
Episodio 29000 completado.
Episodio 30000 completado.
Episodio 31000 completado.
Episodio 32000 completado.
Episodio 33000 completado.
Episodio 34000 completado.
Episodio 35000 completado.
Episodio 36000 completado.
Episodio 37000 completado.
Episodio 3

In [6]:
class AgenteIA:
    def __init__(self, profundidad=4, poda_alpha_beta=True):
        self.profundidad = profundidad
        self.poda_alpha_beta = poda_alpha_beta

    def evaluar_ventana(self, ventana, jugador):
        puntuacion = 0
        oponente = 3 - jugador  

        # 4 en línea → Victoria
        if np.count_nonzero(ventana == jugador) == 4:  
            puntuacion += 1000  
        elif np.count_nonzero(ventana == jugador) == 3 and np.count_nonzero(ventana == 0) == 1:
            puntuacion += 100  # Muy fuerte
        elif np.count_nonzero(ventana == jugador) == 2 and np.count_nonzero(ventana == 0) == 2:
            puntuacion += 10  # Buena jugada
        elif np.count_nonzero(ventana == oponente) == 3 and np.count_nonzero(ventana == 0) == 1:
            puntuacion -= 100  # Bloquear jugada peligrosa
        elif np.count_nonzero(ventana == oponente) == 2 and np.count_nonzero(ventana == 0) == 2:
            puntuacion -= 10  # Bloqueo medio

        return puntuacion


    def evaluar_posicion(self, tablero, jugador):
        if tablero.verificar_victoria(jugador):
            return 1000
        elif tablero.verificar_victoria(3 - jugador):  
            return -1000
        else:
            return random.randint(-10, 10)  

    def minimax(self, tablero, profundidad, alpha, beta, maximizando):
        if profundidad == 0 or tablero.verificar_victoria(Conecta4.JUGADOR) or tablero.verificar_victoria(Conecta4.IA) or tablero.tablero_lleno():
            return self.evaluar_posicion(tablero, Conecta4.IA)

        movimientos = tablero.obtener_movimientos_validos()

        if maximizando:  
            max_eval = -np.inf
            for columna in movimientos:
                tablero_copia = tablero.clonar_tablero()
                tablero_copia.realizar_movimiento(columna, Conecta4.IA)
                evaluacion = self.minimax(tablero_copia, profundidad - 1, alpha, beta, False)
                max_eval = max(max_eval, evaluacion)

                if self.poda_alpha_beta:
                    alpha = max(alpha, evaluacion)
                    if beta <= alpha:
                        break  
            return max_eval
        else:  
            min_eval = np.inf
            for columna in movimientos:
                tablero_copia = tablero.clonar_tablero()
                tablero_copia.realizar_movimiento(columna, Conecta4.JUGADOR)
                evaluacion = self.minimax(tablero_copia, profundidad - 1, alpha, beta, True)
                min_eval = min(min_eval, evaluacion)

                if self.poda_alpha_beta:
                    beta = min(beta, evaluacion)
                    if beta <= alpha:
                        break  
            return min_eval

    def mejor_movimiento(self, tablero):
        """ Calcula el mejor movimiento disponible usando Minimax """
        mejor_columna = random.choice(tablero.obtener_movimientos_validos())  
        mejor_valor = -np.inf
        alpha, beta = -np.inf, np.inf

        for columna in tablero.obtener_movimientos_validos():
            tablero_copia = tablero.clonar_tablero()
            tablero_copia.realizar_movimiento(columna, Conecta4.IA)
            valor_movimiento = self.minimax(tablero_copia, self.profundidad, alpha, beta, False)

            if valor_movimiento > mejor_valor:
                mejor_valor = valor_movimiento
                mejor_columna = columna

        return mejor_columna

In [ ]:
import random
import numpy as np
import multiprocessing

agente_td = AgenteTD(jugador=Conecta4.IA)
agente_minimax = AgenteIA(profundidad=4)  # Oponente más fuerte con poda alfa-beta

episodios = 500
epsilon = 1.0  # Para exploración ε-greedy
epsilon_min = 0.1
epsilon_decay = 0.99995  # Decaimiento de exploración

recompensas = []

def entrenar_td(episodio):
    global epsilon
    juego = Conecta4()
    estado = agente_td.obtener_estado(juego.tablero)
    turno = agente_td.jugador
    recompensa = 0

    while not juego.tablero_lleno():
        if turno == agente_td.jugador:
            if random.random() < epsilon:  # Exploración
                accion = random.choice(juego.obtener_movimientos_validos())
            else:  # Explotación
                accion = agente_td.elegir_accion(juego)

            juego.realizar_movimiento(accion, agente_td.jugador)

            if juego.verificar_victoria(agente_td.jugador):
                recompensa = 1
                nuevo_estado = agente_td.obtener_estado(juego.tablero)
                agente_td.actualizar(estado, accion, recompensa, nuevo_estado, [])
                break

            nuevo_estado = agente_td.obtener_estado(juego.tablero)
            acciones_siguientes = juego.obtener_movimientos_validos()
            agente_td.actualizar(estado, accion, 0, nuevo_estado, acciones_siguientes)
            estado = nuevo_estado
            turno = Conecta4.JUGADOR

        else:
            accion_oponente = agente_minimax.mejor_movimiento(juego)  # Oponente más fuerte
            juego.realizar_movimiento(accion_oponente, Conecta4.JUGADOR)
            if juego.verificar_victoria(Conecta4.JUGADOR):
                recompensa = -1
                nuevo_estado = agente_td.obtener_estado(juego.tablero)
                agente_td.actualizar(estado, accion, recompensa, nuevo_estado, [])
                break
            turno = agente_td.jugador

    if juego.tablero_lleno() and not juego.verificar_victoria(agente_td.jugador) and not juego.verificar_victoria(Conecta4.JUGADOR):
        recompensa = 0.5  # Empate
        agente_td.actualizar(estado, accion, recompensa, agente_td.obtener_estado(juego.tablero), [])

    recompensas.append(recompensa)
    epsilon = max(epsilon_min, epsilon * epsilon_decay)  # Reducir exploración con el tiempo
    print("Episodio "+ episodio)
    if (episodio + 1) % 1000 == 0:
        print(f"Episodio {episodio + 1}: recompensa promedio {np.mean(recompensas[-1000:])}")

# Paralelización opcional
with multiprocessing.Pool() as pool:
    pool.map(entrenar_td, range(episodios))


In [7]:
def jugar_partida(agente1, agente2, mostrar=False):
    juego = Conecta4()
    jugador_actual = Conecta4.JUGADOR  # Agente 1

    while not juego.tablero_lleno():
        if mostrar:
            juego.imprimir_tablero()

        if jugador_actual == Conecta4.JUGADOR:
            columna = agente1.mejor_movimiento(juego) if hasattr(agente1, 'mejor_movimiento') else agente1.elegir_accion(juego)
            juego.realizar_movimiento(columna, Conecta4.JUGADOR)
            if juego.verificar_victoria(Conecta4.JUGADOR):
                return 1  # Gana agente1
            jugador_actual = Conecta4.IA
        else:
            columna = agente2.mejor_movimiento(juego) if hasattr(agente2, 'mejor_movimiento') else agente2.elegir_accion(juego)
            juego.realizar_movimiento(columna, Conecta4.IA)
            if juego.verificar_victoria(Conecta4.IA):
                return 2  # Gana agente2
            jugador_actual = Conecta4.JUGADOR

    return 0  # Empate


In [8]:
def simular_enfrentamientos(agente1, agente2, n=50):
    resultados = {1: 0, 2: 0, 0: 0}  # {agente1, agente2, empate}
    for i in range(n):
        resultado = jugar_partida(agente1, agente2)
        resultados[resultado] += 1
        print(f"Partida {i + 1}: {resultado}")
    return resultados


In [9]:
def jugar_contra_td(agente_td, jugador_humano=1):
    juego = Conecta4()
    turno = jugador_humano  # Comienza el humano si es 1, de lo contrario inicia el agente

    print("🎮 ¡Empieza el juego! Tú eres el jugador", jugador_humano)
    juego.imprimir_tablero()

    while not juego.tablero_lleno():
        if turno == jugador_humano:
            try:
                columna = int(input("Selecciona una columna (0-6): "))
                if columna < 0 or columna >= juego.COLUMNAS:
                    print("❌ Columna inválida.")
                    continue
                if not juego.realizar_movimiento(columna, jugador_humano):
                    print("❌ Columna llena.")
                    continue
            except ValueError:
                print("⚠️ Ingresa un número válido.")
                continue

            if juego.verificar_victoria(jugador_humano):
                juego.imprimir_tablero()
                print("🎉 ¡Has ganado!")
                return

            turno = 3 - jugador_humano  # Cambia de turno
        else:
            print("🤖 Turno del agente...")
            columna = agente_td.elegir_accion(juego)
            juego.realizar_movimiento(columna, agente_td.jugador)
            if juego.verificar_victoria(agente_td.jugador):
                juego.imprimir_tablero()
                print("💻 El agente ha ganado.")
                return

            turno = jugador_humano

        juego.imprimir_tablero()

    print("🤝 ¡Empate!")


jugar_contra_td(agente_td)


🎮 ¡Empieza el juego! Tú eres el jugador 1
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
🤖 Turno del agente...
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 2 0 0 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 2 0 0 0]]
🤖 Turno del agente...
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 2 0 2 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 2 0 2 0]]
🤖 Turno del agente...
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 2 2 2 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 2 2 2 0]]
🎉 ¡Has ganado!


In [10]:



# Esto es IA vs IA (NO EJECUTAR)





# agente_td = AgenteTD(jugador=Conecta4.JUGADOR)  # Entrenado antes
agente_minimax = AgenteIA(profundidad=4, poda_alpha_beta=False)
agente_minimax_ab = AgenteIA(profundidad=4, poda_alpha_beta=True)

# TD vs Minimax
# res_td_vs_min = simular_enfrentamientos(agente, agente_minimax)

# TD vs Minimax con poda
res_td_vs_ab = simular_enfrentamientos(agente_td, agente_minimax_ab)

# Minimax vs Minimax con poda
# res_min_vs_ab = simular_enfrentamientos(agente_minimax, agente_minimax_ab)


Partida 1: 2
Partida 2: 2
Partida 3: 2
Partida 4: 2
Partida 5: 2
Partida 6: 2
Partida 7: 2
Partida 8: 2
Partida 9: 2
Partida 10: 2


KeyboardInterrupt: 

In [ ]:

labels = ['Agente TD', 'Minimax', 'Minimax AB']
victorias = [
    res_td_vs_min[1],
    res_td_vs_min[2],
    0
]

victorias[0] += res_td_vs_ab[1]
victorias[2] += res_td_vs_ab[2]
victorias[1] += res_min_vs_ab[1]
victorias[2] += res_min_vs_ab[2]

plt.bar(labels, victorias)
plt.title("Victorias de los Agentes en 150 partidas")
plt.ylabel("Cantidad de Victorias")
plt.savefig("resultados_agentes.png")
plt.show()
